spring:
  datasource:
    url: jdbc:h2:mem:oreo;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: false
  mail:
    host: ${MAIL_HOST:localhost}
    port: ${MAIL_PORT:1025}
    username: ${MAIL_USERNAME:demo}
    password: ${MAIL_PASSWORD:demo}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
logging:
  level:
    root: INFO
    com.oreo.insightfactory: DEBUG
